baseurl = "https://anthonygraca.io/"
contentdir = "content"
publishdir = "public"

canonifyurls = true
relativeURLS = false


title = "blog | Anthony Graca"
languageCode = "en-us"
summaryLength = 42

copyright = "copyright info, like license, year, author name, e.t.c."

[module]
  [[module.imports]]
    theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]

[author]
name = "Your Name"

[params]
description = "Something about your blog"
showFooterCredits = true
math = false
useIcon = true

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss+xml"
baseName = "feed"



[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true

