baseurl = "/"
contentdir = "content"
publishdir = "public"

canonifyurls = true
relativeURLS = false

theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
title = "My awesome blog"
languageCode = "en-us"
summaryLength = 42

copyright = "copyright info, like license, year, author name, e.t.c."

[author]
name = "Your Name"

[params]
description = "Something about your blog"
showFooterCredits = true
math = false
useIcon = true

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss+xml"
baseName = "feed"
